name: pg-cron
services:
  postgres:
    build: .
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--data-checksums"
      SHARED_PRELOAD_LIBRARIES: "pg_cron"
      CRON_DATABASE: "postgres"
      TZ: "Asia/Shanghai"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=postgres"
      - "-c"
      - "cron.timezone='Asia/Shanghai'"

volumes:
  postgres_data: 